version: "3.8"
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    ports:
      - 8080:8080
    env_file:
      - ../.env
    restart: always
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - nisits-scan:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../.env
volumes:
  nisits-scan:
